export const PAYMENT_PAGE ={
SATISFACTION_TITLE : "100% satisfaction guarantee",
SATISFACTION_PARA:  "Place your order with peace of mind",
SUMMARY_TEXT : "Order summary",
SUMMARY_ITEMS: "1 item",
INSURANCE_TEXT: "Add travels insurance for $450.00",
// INFO_ICON: "info",
SUBTOTAL: "Subtotal",
SUBTOTAL_VALUE: "$1200.99",
ADDED_FEES: "Added fees",
FEES_VALUE: "$200.50",
VAT:"VAT",
VAT_VALUE: "$300.62",
TOTAL: "Total",
TOTAL_VALUE: "$16,000.61",
PROMO_TEXT: "Add promo code or gift card",
ADD_BTN: "+ Add",
TERMS_TEXT: " By placing your order you agree to be bound by the sites ",
TERMS_TEXT2: "and",
TERMS_TEXT3: "Your credit/debit card will be",
TERMS_TEXT4: "Your statement will reflect the final order total after completion. Events may charge retailers free in connection with orders placed using our services.",
HIGHLIGHT_TEXT: "Terms of Service",
HIGHLIGHT_TEXT2: "Privacy Policy.",
STYLED_TEXT: " temporarily authorized for $50.",
STYLED_TEXT2: "Learn more",
VENUE_TEXT: "Silverstone Event Center",
VENUE_ADDRESS: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
// TICK_ICON: "check_circle",
PAYMENT_SUCESS: "Payment Success!",
DETAILS: "Details",
REFERENCE_TEXT: "Reference Number",
REF_VALUE: "000573468374",
REFERENCE_TEXT2: "Date",
REF_VALUE2: "July 11, 2023",
REFERENCE_TEXT3: "Time",
REF_VALUE3: "12:18 AM",
REFERENCE_TEXT4: "Payment Method",
REF_VALUE4: "Credit Card",
TOTAL_AMOUNT: "Amount",
AMOUNT_VALUE: "$16,000.61",
// DOWNLOAD_ICON: "download",
DOWNLOAD_TEXT: "Download Receipt",
// SHARE_I: " share",
SHARE_TEXT: "Share",
CANCEL_TEXT: "Cancel"
}
