export const SUBSCRIPTIONS_ENUM = {
  MARKETING_LINE:
    "For the new marketer on a budget who just wants basic tracking...",
  CHOOSE_PLAN: "Choose your plan",
  ENJOY_MESSAGE:
    "enjoy 14 days free trial. No contract or credit card required.",
  MONTH: "Monthly",
  YEAR: "Yearly",
  MO: "/mo",
  DISCOUNT: "15% OFF",
  ACCESS: "Access to basic features",
  DOWNLOAD: "Download up to 10 events",
  AUDIT: "Audit log and note",
  STORGE: "20GB individual data",
  CHAT: "Basic chat support",
  DOWNLOAD_1: "Download up to 30 events",
  ADVANCE_FEATURES: "Advanced audit log and note",
  MORE_STORAGE: "100GB individual data",
  CHAT_SUPPORT: "Standard chat support",
  BACKUP: "Backup and restore",
  SERVICE: "Personalized service",
  ADVANCE_DOWNLOADS: "Download all events",
  SUPER_STORAGE: "1TB individual data",
  SKIP_TRIAL: "or skip trial and",
  BUY_NOW: "buy now",
  AGREE: "Agree to the",
  TERMS: "Terms of Use",
  PRIVACY: "Privacy Policy",
  GET_STARTED: "Get started",
  SKIP_TRIAL_1: "or skip trial and buy now",
  ADD_MORE: "+ many more",
  ADVANCE_AUDIT: "Advance audit log and note",
  AND: "and",
  ATTENDANCE: "200+ online attendance",
};
