export const SUBSCRIPTIONS_ENUM = {  marketing_line :
  "For the new marketer on a budget who just wants basic tracking...",
  CHOOSE_PLAN : "Choose your plan",
  enjoy_message :
  "enjoy 14 days free trial. No contract or credit card required.",
  month : "Monthly",
  year : "Yearly",
  mo : "/mo",
  discount : "15% OFF",
  access : "Access to basic features",
  download : "Download up to 10 events",
  audit : "Audit log and note",
  storge : "20GB individual data",
  chat : "Basic chat support",
  download_1 : "Download up to 30 events",
  advance_features : "Advanced audit log and note",
  more_storage : "100GB individual data",
  chat_support : "Standard chat support",
  backup : "Backup and restore",
  service : "Personalized service",
  advance_downloads : "Download all events",
  super_storage : "1TB individual data",
  skip_trial : "or skip trial and",
  buy_now : "buy now",
  agree : "Agree to the",
  terms : "Terms of Use",
  privacy : "Privacy Policy",
  get_started : "Get started",
  skip_trial_1 : "or skip trial and buy now",
  add_more : "+ many more",
  advance_audit : "Advance audit log and note",
  and : "and",
  attendance : "200+ online attendance",
}