import venueImg1 from "../assets/venue_imgs/venueImg1.jpeg";
import venueImg2 from "../assets/venue_imgs/venueImg2.jpg";
import venueImg3 from "../assets/venue_imgs/venueImg3.jpeg";
import venueImg4 from "../assets/venue_imgs/venueImg4.jpeg";
import venueImg5 from "../assets/venue_imgs/venueImg5.jpeg";
import venueImg6 from "../assets/venue_imgs/venueImg6.jpeg";

export const eventsMetadata = [
  {
    eventName: "Tech Innovators Summit 2026",
    eventType: "CONFERENCE",
    description:
      "Annual technology summit featuring AI, Cloud, and Cybersecurity leaders.",
    venue: "Hyderabad International Convention Centre (HICC)",
    city: "Hyderabad",
    state: "Telangana",
    location: "https://maps.app.goo.gl/4H9x6wF4gKetNCqb9",
    eventDate: "2026-02-15",
    eventTime: "09:00",
    image: venueImg1,
    expectedAttendees: 2500,
    comments:
      "Requires high-speed dedicated internet and simultaneous translation support.",
    available: false,
  },
  {
    eventName: "Startup Pitch Fest 2026",
    eventType: "STARTUP_PITCH",
    description:
      "Early-stage startups pitching to venture capitalists and angel investors.",
    venue: "KTPO Convention Centre",
    city: "Bengaluru",
    state: "Karnataka",
    location: "https://maps.app.goo.gl/4H9x6wF4gKetNCqb9",
    eventDate: "2026-03-10",
    eventTime: "10:30",
    image: venueImg2,
    expectedAttendees: 800,
    comments: "Investor networking lounge required.",
    available: true,
  },
  {
    eventName: "Healthcare & Pharma Expo 2026",
    eventType: "EXHIBITION_EXPO",
    description:
      "Exhibition showcasing pharmaceutical innovations and medical equipment.",
    venue: "Chennai Trade Centre",
    city: "Chennai",
    state: "Tamil Nadu",
    location: "https://maps.app.goo.gl/4H9x6wF4gKetNCqb9",
    eventDate: "2026-04-05",
    eventTime: "11:00",
    image: venueImg3,
    expectedAttendees: 5000,
    comments: "Large booth setup and medical compliance required.",
    available: true,
  },
  {
    eventName: "Global Leadership Conference",
    eventType: "CORPORATE_EVENT",
    description:
      "Executive-level conference focusing on governance and business strategy.",
    venue: "Novotel Visakhapatnam Varun Beach",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    location: "https://maps.app.goo.gl/4H9x6wF4gKetNCqb9",
    eventDate: "2026-02-22",
    eventTime: "14:00",
    image: venueImg4,
    expectedAttendees: 600,
    comments: "VIP security arrangements required.",
    available: true,
  },
  {
    eventName: "AI & Data Engineering Workshop",
    eventType: "WORKSHOP",
    description:
      "Hands-on workshop covering GenAI, LLM integration, and data pipelines.",
    venue: "T-Hub Phase 2",
    city: "Hyderabad",
    state: "Telangana",
    location: "https://maps.app.goo.gl/4H9x6wF4gKetNCqb9",
    eventDate: "2026-02-28",
    eventTime: "09:30",
    image: venueImg5,
    expectedAttendees: 300,
    comments: "Laptop seating with charging ports required.",
    available: false,
  },
  {
    eventName: "National HR Conclave 2026",
    eventType: "SEMINAR",
    description: "HR leaders discussing future workforce and AI hiring trends.",
    venue: "ITC Gardenia",
    city: "Bengaluru",
    state: "Karnataka",
    location: "https://maps.app.goo.gl/4H9x6wF4gKetNCqb9",
    eventDate: "2026-03-18",
    eventTime: "10:00",
    image: venueImg6,
    expectedAttendees: 1200,
    comments: "Panel discussion stage with LED backdrop.",
    available: true,
  },
  {
    eventName: "EV Automotive Product Launch",
    eventType: "PRODUCT_LAUNCH",
    description:
      "Launch event for a new electric vehicle model with live media coverage.",
    venue: "The Leela Palace Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    location: "https://maps.app.goo.gl/4H9x6wF4gKetNCqb9",
    eventDate: "2026-04-12",
    eventTime: "18:00",
    image: venueImg2,
    expectedAttendees: 900,
    comments: "Live streaming and media coverage required.",
    available: true,
  },
  {
    eventName: "Annual Corporate Townhall",
    eventType: "TOWNHALL",
    description:
      "Company-wide strategy presentation and employee recognition awards.",
    venue: "Hyatt Regency Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    location: "https://maps.app.goo.gl/4H9x6wF4gKetNCqb9",
    eventDate: "2026-01-30",
    eventTime: "15:00",
    image: venueImg3,
    expectedAttendees: 1500,
    comments: "Hybrid mode with remote live broadcast.",
    available: false,
  },
];

export const EVENT_TYPE_OPTIONS = [
  { value: "CONFERENCE", label: "Conference" },
  { value: "WORKSHOP", label: "Workshop" },
  { value: "SEMINAR", label: "Seminar" },
  { value: "PRODUCT_LAUNCH", label: "Product Launch" },
  { value: "CORPORATE_EVENT", label: "Corporate Event" },
  { value: "TOWNHALL", label: "Townhall" },
  { value: "EXHIBITION_EXPO", label: "Exhibition / Expo" },
  { value: "STARTUP_PITCH", label: "Startup Pitch Event" },
  { value: "NETWORKING_EVENT", label: "Networking Event" },
  { value: "TRAINING_PROGRAM", label: "Training Program" },
  { value: "WEBINAR", label: "Webinar" },
  { value: "HACKATHON", label: "Hackathon" },
  { value: "AWARD_CEREMONY", label: "Award Ceremony" },
  { value: "WEDDING", label: "Wedding" },
  { value: "SOCIAL_GATHERING", label: "Social Gathering" },
  { value: "GOVERNMENT_EVENT", label: "Government Event" },
];

export const EVENT_STATUSES = [
  { value: "pending", label: "Pending" },
  { value: "assigned", label: "Assigned" },
  { value: "accepted", label: "Accepted" },
  { value: "ready", label: "Ready" },
  { value: "in_progress", label: "In Progress" },
  { value: "completed", label: "Completed" },
  { value: "declined", label: "Declined" },
  { value: "cancelled", label: "Cancelled" },
  { value: "deleted", label: "Deleted" },
];
