export const paths = {
  home: "/",
  login: "/login",
  newsFeed: "/news-feed",
  accountSettings: "/account-settings",
  eventsDashboard: "/events-dashboard",
  tasks: "/tasks",
  createTask: "/tasks/create",
  registration: "/registration",
  twoFactorAuth: "/two-factor-auth",
  eventsDetails: "/events/event-details",
  createEvent: "/events/create-event",
  editEvent: "/events/edit-event",
  aboutUs: "/about-us",

  vendor: "/vendor",
  supervisor: "/supervisor",
  // customer: "/customer",
  qa: "/qa",
  userManagement: "/user/management",
  marketPlace: "/market-place",
  getInTouch: "/get-in-touch",

  venues: "/venues",
};
